global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs: 
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['211.183.3.101:9100', '211.183.3.102:9100']
