version: '3.7'
services:
  main:
    image: 211.183.3.103:9999/public-repo/main:1.0
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        max_attempts: 2
    networks:
      - default_proxy
    environment:
      SERVICE_PORTS: 80
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: # -p option, attached to ingress network
      - "8003:80"
    networks:
      - default_proxy
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

networks:
  default_proxy:
    external: true
