version: '3.7'
services:
  stocks:
    image: 211.183.3.103:9999/public-repo/crypto:1.0
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
        max_attempts: 2
    environment:
      SERVICE_PORTS: 80
    networks:
      - crypto
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - crypto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: # -p option, attached to ingress network
      - "8002:80"
    networks: # backend network -> nginx containers
      - crypto
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
networks:
  crypto:
    external: true                                                                       

